make_dataset:
  test_size: 0.1
  random_state: 30

data_preprocessing:
  percentiles:
    - 0.002
    - 0.998

train_model:
  random_forest_regressor:
    n_estimators: 30    # Change the number of estimators to a higher number to get better results
    max_depth: 6
    verbose: 2
    n_jobs: -1